# Generated by Django 5.0.1 on 2024-02-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='checkin_time',
            new_name='checkinTime',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='checkout_time',
            new_name='checkoutTime',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='order_date',
            new_name='orderDate',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='order_time',
            new_name='orderTime',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='bed_type',
            new_name='bed',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_type',
            new_name='room',
        ),
    ]
