# Generated by Django 5.0.1 on 2024-02-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_room_bookings_idroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='checkinTime',
            new_name='checkin_time',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='checkoutTime',
            new_name='checkout_time',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='orderDate',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='orderTime',
            new_name='order_time',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='idRoom',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='bed',
            new_name='bed_type',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='cancel',
            new_name='cancellation_policy',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='room_type',
        ),
    ]
