# Generated by Django 5.0.1 on 2024-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_checkin_time_bookings_checkintime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
