# Generated by Django 5.0.1 on 2024-02-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_contact_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard_bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('orderDate', models.CharField(max_length=15)),
                ('orderTime', models.TimeField()),
                ('checkin', models.CharField(max_length=25)),
                ('checkinTime', models.TimeField()),
                ('checkout', models.CharField(max_length=25)),
                ('checkoutTime', models.TimeField()),
                ('notes', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('idRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
