# Generated by Django 5.0.1 on 2024-02-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dashboard_bookings_delete_bookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dashboard_bookings',
            new_name='Bookings',
        ),
    ]
