# Generated by Django 5.0.1 on 2024-02-13 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room'),
        ),
    ]
