# Generated by Django 5.0.1 on 2024-02-15 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=25)),
                ('hour', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=35)),
                ('telephone', models.CharField(max_length=35)),
                ('archived', models.BooleanField(default=False)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=20)),
                ('bed', models.CharField(max_length=5)),
                ('facilities', models.JSONField()),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('cancel', models.TextField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FO', 'Food'), ('CL', 'Clean'), ('OT', 'Other')], max_length=2)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='website.room')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('orderDate', models.CharField(max_length=15)),
                ('orderTime', models.TimeField()),
                ('checkin', models.CharField(max_length=25)),
                ('checkinTime', models.TimeField()),
                ('checkout', models.CharField(max_length=25)),
                ('checkoutTime', models.TimeField()),
                ('notes', models.TextField()),
                ('status', models.CharField(max_length=25)),
                ('idRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.room')),
            ],
        ),
    ]
