name: Deploy EC2 HM Django

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Run commands on the server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd django-dashboard
            git pull origin main
            pip install -r requirements.txt
            sudo /home/ubuntu/env/bin/python3 manage.py collectstatic
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
