name: Deploy to HotelMiranda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} #ip publica
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            git pull origin main
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            sudo /home/ubuntu/env/bin/python3 manage.py collectstatic
      
      - name: Set up environment variables
        env:
          SQL_HOST: ${{ secrets.SQL_HOST }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}