name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run commands on the server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd django_dashboard
            git pull origin main
            pip install -r requirements.txt
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            sudo /home/ubuntu/env/bin/python3 manage.py collectstatic
      
      # - name: Set up environment variables
      #   env:
      #     SQL_HOST: ${{ secrets.SQL_HOST }}
      #     SQL_USER: ${{ secrets.SQL_USER }}
      #     SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      #     SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
